[package]
name = "myfirstrust"
version = "0.1.0"
authors = ["nugrohoac96 <nugrohoac96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
